const TOKEN_KEY = "@&#%@@EDJFJHFBDHBCSfkjvniuiH*&Y$&*yhuH*&$YT*UIHBNJFBVHAGCVSFC@%RE&^@*&@EUIHDUIS";
const REFRESH_TOKEN_KEY = "@&#%@@EDJFJHFBDHBCSJBHSCGDyt%##@^!&&*^%HSCGHVHbxhjbcbdjduJEGFEIY&U#EHUhbed(#*&E&@^#(@*#@%#@RDGHVHAGCVSFC@%RE&^@*&@EUIHDUIS";
module.exports = {TOKEN_KEY,REFRESH_TOKEN_KEY}
